'use client';

/**
 * Barcode scan station (Phase 5): keyboard-wedge scanner + manual entry →
 * authoritative backend lookup → variant, SKU and inventory. Never mutates
 * stock directly: adjustments route through the existing inventory page.
 * Labels print via a print stylesheet (window.print precedent exists).
 */

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';

import {
  assignVariantBarcode,
  lookupVariantByBarcode,
  type BarcodeLookupResult,
} from '../../../../lib/admin-api';
import { barcodeDisplayType, isInternalBarcode, renderEan13Svg } from '../../../../lib/barcode';
import { AdminStatusBadge } from '../../../../components/admin';
import { useConfirm } from '../../../../components/ConfirmDialog';
import { useToast } from '../../../../components/Toast';

type LabelJob = { lookup: BarcodeLookupResult; copies: number };

function BarcodeGraphic({ barcode }: { barcode: string }) {
  const rendered = renderEan13Svg(barcode);
  if (!rendered) {
    return <p className="barcode-label__text-only">{barcode}</p>;
  }
  // SVG is generated by our own EAN-13 encoder (no user HTML involved).
  return (
    <div
      className="barcode-graphic"
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: rendered.svg }}
      role="img"
      aria-label={`Barcode ${barcode}`}
    />
  );
}

function BarcodeLabel({ job, showPrice }: { job: LabelJob; showPrice: boolean }) {
  const { lookup } = job;
  const variantLabel = Object.values(lookup.attributes).join(' / ') || lookup.variant.name || lookup.variant.sku;
  return (
    <div className="barcode-label">
      <p className="barcode-label__brand">JB Mercantile</p>
      <p className="barcode-label__product">{lookup.product.name}</p>
      <p className="barcode-label__variant">{variantLabel}</p>
      <p className="barcode-label__sku">SKU {lookup.variant.sku}</p>
      <BarcodeGraphic barcode={lookup.variant.barcode ?? ''} />
      <p className="barcode-label__digits">{lookup.variant.barcode}</p>
      {showPrice && lookup.variant.price !== null && (
        <p className="barcode-label__price">KSh {Number(lookup.variant.price).toLocaleString('en-KE', { minimumFractionDigits: 2 })}</p>
      )}
    </div>
  );
}

export default function AdminScanPage() {
  const { notify } = useToast();
  const { confirm, dialog } = useConfirm();
  const inputRef = useRef<HTMLInputElement>(null);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<BarcodeLookupResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [history, setHistory] = useState<Array<{ barcode: string; sku: string | null; at: string }>>([]);
  const [labels, setLabels] = useState<LabelJob[]>([]);
  const [showPrice, setShowPrice] = useState(true);
  const [printing, setPrinting] = useState(false);
  const [replaceOpen, setReplaceOpen] = useState(false);
  const [replaceValue, setReplaceValue] = useState('');
  const [replaceSource, setReplaceSource] = useState('MANUFACTURER');
  const [replaceReason, setReplaceReason] = useState('');

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const submit = async (raw?: string) => {
    const value = (raw ?? input).trim();
    if (!value) return;
    setBusy(true);
    setError(null);
    try {
      const lookup = await lookupVariantByBarcode(value);
      setResult(lookup);
      setReplaceOpen(false);
      setHistory((prev) => [{ barcode: value, sku: lookup.variant.sku, at: new Date().toLocaleTimeString('en-KE') }, ...prev].slice(0, 10));
    } catch (e) {
      setResult(null);
      const message = e instanceof Error ? e.message : 'Lookup failed.';
      setError(message);
      setHistory((prev) => [{ barcode: value, sku: null, at: new Date().toLocaleTimeString('en-KE') }, ...prev].slice(0, 10));
    } finally {
      setBusy(false);
      setInput('');
      inputRef.current?.focus();
    }
  };

  const addLabel = (copies: number) => {
    if (!result?.variant.barcode) return;
    setLabels((prev) => {
      const existing = prev.find((job) => job.lookup.variant.id === result.variant.id);
      if (existing) {
        return prev.map((job) => (job.lookup.variant.id === result.variant.id ? { ...job, copies: job.copies + copies } : job));
      }
      return [...prev, { lookup: result, copies }];
    });
    notify('success', `Added ${copies} label(s) for ${result.variant.sku}.`);
  };

  const handleReplace = async () => {
    if (!result) return;
    if (replaceValue.trim().length < 1 || replaceReason.trim().length < 3) {
      notify('error', 'Enter the replacement barcode and a reason (min 3 characters).');
      return;
    }
    const confirmed = await confirm({
      title: 'Replace barcode?',
      description: `${result.variant.sku}: ${result.variant.barcode} → ${replaceValue.trim()}. The old code stops resolving and the change is audited.`,
      confirmLabel: 'Replace barcode',
      variant: 'warning',
      onConfirm: () => undefined,
    });
    if (!confirmed) return;
    try {
      // Product id is needed for the product-scoped route; resolve via the
      // looked-up variant (same-product guard enforced server-side).
      const updated = await assignVariantBarcode(result.product.id, result.variant.id, {
        barcode: replaceValue.trim(),
        source: replaceSource,
        replace: true,
        reason: replaceReason.trim(),
      });
      notify('success', `Barcode replaced: ${updated.barcode}.`);
      setReplaceOpen(false);
      setReplaceValue('');
      setReplaceReason('');
      await submit(updated.barcode);
    } catch (e) {
      notify('error', e instanceof Error ? e.message : 'Replacement failed.');
    }
  };

  return (
    <div className="account-page">
      {dialog}
      <header className="account-page__header">
        <div>
          <Link href="/admin/inventory" className="text-button">← Back to Inventory</Link>
          <h1 style={{ marginTop: '0.5rem' }}>Scan station</h1>
          <p className="muted-copy">USB/Bluetooth scanners type into the field below — press Enter to look up. No camera needed.</p>
        </div>
      </header>

      <section className="workspace-card" aria-labelledby="scan-input-heading">
        <h2 id="scan-input-heading">Scan barcode</h2>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            void submit();
          }}
          className="scan-form"
        >
          <label>
            <span>Barcode value</span>
            <input
              ref={inputRef}
              type="text"
              value={input}
              autoComplete="off"
              autoCorrect="off"
              autoCapitalize="off"
              spellCheck={false}
              placeholder="Scan or type, then Enter"
              onChange={(e) => setInput(e.currentTarget.value)}
              aria-describedby="scan-hint"
            />
          </label>
          <button type="submit" className="button" disabled={busy || !input.trim()} aria-busy={busy}>
            {busy ? 'Looking up…' : 'Look up'}
          </button>
        </form>
        <p id="scan-hint" className="muted-copy">Scanner sends the value + Enter automatically when this field is focused.</p>
        {error && (
          <div className="error-message" role="alert">
            <p><strong>Barcode not found.</strong> {error}</p>
            <p className="muted-copy">Check the digits and try again, or find the variant in <Link href="/admin/inventory">inventory search</Link> to assign this code.</p>
          </div>
        )}
      </section>

      {result && (
        <section className="workspace-card" aria-labelledby="scan-result-heading" aria-live="polite">
          <h2 id="scan-result-heading">Scan result</h2>
          <dl className="media-meta">
            <dt>Product</dt>
            <dd><Link href={`/admin/products/${result.product.id}`}>{result.product.name}</Link> <AdminStatusBadge status={result.product.status} /></dd>
            <dt>Variant</dt>
            <dd>{Object.values(result.attributes).join(' / ') || result.variant.name || '—'}</dd>
            <dt>SKU</dt>
            <dd><code>{result.variant.sku}</code></dd>
            <dt>Barcode</dt>
            <dd>
              <code>{result.variant.barcode}</code>{' '}
              <span className="muted-copy">
                {barcodeDisplayType(result.variant.barcode ?? '')}
                {isInternalBarcode(result.variant.barcode ?? '') ? ' · internal (store use only)' : ''}
              </span>
            </dd>
            <dt>Price</dt>
            <dd>{result.variant.price === null ? 'Inherits product price' : `KSh ${Number(result.variant.price).toLocaleString('en-KE', { minimumFractionDigits: 2 })}`}</dd>
            <dt>Stock</dt>
            <dd>
              {result.inventory
                ? `${result.inventory.availableQuantity.toLocaleString('en-KE')} available (${result.inventory.quantityOnHand} on hand − ${result.inventory.quantityReserved} reserved)`
                : 'No inventory record'}
            </dd>
            <dt>Status</dt>
            <dd><AdminStatusBadge status={result.variant.status} /></dd>
          </dl>
          <div className="barcode-graphic__preview">
            <BarcodeGraphic barcode={result.variant.barcode ?? ''} />
          </div>
          <div className="form-actions">
            <button type="button" className="button button--secondary" onClick={() => addLabel(1)}>Add label ×1</button>
            <button type="button" className="button button--secondary" onClick={() => addLabel(12)}>Add labels ×12</button>
            <Link href="/admin/inventory" className="button button--secondary">Adjust stock</Link>
            <button type="button" className="text-button" onClick={() => setReplaceOpen((open) => !open)}>
              {replaceOpen ? 'Hide replacement' : 'Replace barcode…'}
            </button>
          </div>
          {replaceOpen && (
            <div className="form-grid">
              <label>
                <span>Replacement barcode *</span>
                <input type="text" value={replaceValue} maxLength={48} onChange={(e) => setReplaceValue(e.currentTarget.value)} />
              </label>
              <label>
                <span>Source</span>
                <select value={replaceSource} onChange={(e) => setReplaceSource(e.currentTarget.value)}>
                  <option value="MANUFACTURER">Manufacturer</option>
                  <option value="SUPPLIER">Supplier</option>
                  <option value="IMPORTED">Imported</option>
                  <option value="MANUAL">Manual</option>
                  <option value="INTERNAL">Internal</option>
                </select>
              </label>
              <label className="form-field-full">
                <span>Reason * (audited)</span>
                <input type="text" value={replaceReason} maxLength={200} placeholder="Manufacturer reissued identifier…" onChange={(e) => setReplaceReason(e.currentTarget.value)} />
              </label>
              <div className="form-actions">
                <button type="button" className="button" onClick={() => void handleReplace()}>Replace barcode</button>
              </div>
            </div>
          )}
        </section>
      )}

      {labels.length > 0 && (
        <section className="workspace-card" aria-labelledby="label-queue-heading">
          <h2 id="label-queue-heading">Label queue ({labels.reduce((total, job) => total + job.copies, 0)} labels)</h2>
          <label className="variant-manager__value">
            <input type="checkbox" checked={showPrice} onChange={(e) => setShowPrice(e.currentTarget.checked)} />
            <span>Print price on labels</span>
          </label>
          <ul className="label-queue">
            {labels.map((job) => (
              <li key={job.lookup.variant.id}>
                <span><code>{job.lookup.variant.sku}</code> · {job.lookup.variant.barcode}</span>
                <label>
                  <span className="visually-hidden">Copies for {job.lookup.variant.sku}</span>
                  <input
                    type="number"
                    min="1"
                    max="500"
                    value={job.copies}
                    onChange={(e) => {
                      const copies = Math.max(1, Math.min(500, Number(e.currentTarget.value) || 1));
                      setLabels((prev) => prev.map((entry) => (entry.lookup.variant.id === job.lookup.variant.id ? { ...entry, copies } : entry)));
                    }}
                  />
                </label>
                <button type="button" className="text-button" onClick={() => setLabels((prev) => prev.filter((entry) => entry.lookup.variant.id !== job.lookup.variant.id))}>
                  Remove
                </button>
              </li>
            ))}
          </ul>
          <div className="form-actions">
            <button type="button" className="button" onClick={() => { setPrinting(true); setTimeout(() => window.print(), 50); }}>
              Preview &amp; print labels
            </button>
            <button type="button" className="button button--secondary" onClick={() => setLabels([])}>Clear queue</button>
          </div>
        </section>
      )}

      {history.length > 0 && (
        <section className="workspace-card" aria-labelledby="scan-history-heading">
          <h2 id="scan-history-heading">Recent scans</h2>
          <ul className="scan-history">
            {history.map((entry, index) => (
              <li key={`${entry.barcode}-${index}`}>
                <code>{entry.barcode}</code> → {entry.sku ? <span>{entry.sku}</span> : <span className="muted-copy">not found</span>}{' '}
                <span className="muted-copy">{entry.at}</span>{' '}
                <button type="button" className="text-button" onClick={() => void submit(entry.barcode)}>Rescan</button>
              </li>
            ))}
          </ul>
        </section>
      )}

      {printing && (
        <div className="label-sheet" aria-hidden={false} aria-label="Label print preview">
          {labels.flatMap((job) => Array.from({ length: job.copies }, (_, i) => <BarcodeLabel key={`${job.lookup.variant.id}-${i}`} job={{ ...job, copies: 1 }} showPrice={showPrice} />))}
          <div className="form-actions label-sheet__actions">
            <button type="button" className="button button--secondary" onClick={() => setPrinting(false)}>Back to scan station</button>
          </div>
        </div>
      )}
    </div>
  );
}
